version: "3.9"

services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
        USER_NAME: ${USER_NAME}
    env_file:
      - .env
    volumes:
      - ./docker/php/entrypoint.sh:/entrypoint.sh
      - ./docker/php/app.ini:/usr/local/etc/php/conf.d/app.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./:/home/shashin

  web:
    image: nginx:1.23-alpine
    environment:
      - TZ=Europe/Paris
    depends_on:
      - php
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./:/home/shashin
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf

