rest_api_controllers:
  resource: ../src/Http/RestApi/Controller/
  type: attribute
  prefix: 'api/v1'

web_controllers:
  resource: ../src/Http/Web/Controller/
  type: annotation
  prefix:
    fr: ''
    en: '/en'